version: "3"

tasks:
  newday:
    desc: "Create a new day"
    vars:
      TODAY:
        sh: "date +'%d'"
      THIS_YEAR:
        sh: "date +'%Y'"
      YEAR: "{{default (.THIS_YEAR) .YEAR}}"
      DAY: "{{default (.TODAY) .DAY}}"
    cmds:
      - mkdir -p "{{.YEAR}}/inputs"
      - mkdir -p "{{.YEAR}}/test"
      - printf "from pathlib import Path\n\ndata = Path(\"{{.YEAR}}/inputs/day{{.DAY}}.txt\").read_text().strip()" >> "{{.YEAR}}/day{{.DAY}}a.py"
      - touch "{{.YEAR}}/test/day{{.DAY}}.txt"
      - curl -s "https://adventofcode.com/{{.YEAR}}/day/{{.DAY}}/input" -H "cookie:session=$(cat ./.aoc)" > "{{.YEAR}}/inputs/day{{.DAY}}.txt"