version: "3"

vars:
  TODAY:
    sh: "date +'%d'"
  THIS_YEAR:
    sh: "date +'%Y'"
  YEAR: "{{default (.THIS_YEAR) .YEAR}}"
  DAY: "{{default (.TODAY) .DAY}}"
  DL_DAY:
    sh: "date +'%-d'"

tasks:
  prepare:
    desc: "Prepare directories"
    cmds:
      - mkdir -p "{{.YEAR}}/inputs"
      - mkdir -p "{{.YEAR}}/test"
  dl:
    desc: "Download input"
    cmds:
      - task: prepare
      - curl -s "https://adventofcode.com/{{.YEAR}}/day/{{.DL_DAY}}/input" --cookie "session=$(cat ./.aoc)" > "{{.YEAR}}/inputs/day{{.DAY}}.txt"

  newday:
    desc: "Create a new day"
    cmds:
      - task: prepare
      - task: dl
      - touch "{{.YEAR}}/test/day{{.DAY}}.txt"
      - |
        [ ! -f "{{.YEAR}}/day{{.DAY}}a.py" ] && printf "from pathlib import Path\n\ndata = Path(\"{{.YEAR}}/test/day{{.DAY}}.txt\").read_text().strip()" >> "{{.YEAR}}/day{{.DAY}}a.py"
